export const option = {
  height: "auto",
  calcHeight: 250,
  searchShow: true,
  searchMenuSpan: 4,
  actionBtn: false,
  addBtn: true,
  editBtn: true,
  delBtn: true,
  // alertShow: true,
  border: true,
  index: true,
  // selection: true,
  menuWidth: 400,
  searchHide: true,
  dialogWidth: 800,
  dialogClickModal: false,
  dropSort: true,
  column: [
    {
      label: "工单号",
      prop: "workOrderNbr",
      align: "left",
      search: false,
      sortable: false,
      overHidden: true,
      width: 100,
      span: 24,
    },
    {
      label: "工单任务号",
      prop: "workOrderTask",
      align: "left",
      search: false,
      sortable: false,
      overHidden: true,
      width: 120,
      span: 24,
    },
    {
      label: "工作内容",
      prop: "wrTaskTitle",
      align: "left",
      search: false,
      sortable: false,
      overHidden: true,
      width: 300,
      span: 24,
    },
    {
      label: "计划完工",
      prop: "earlyFinishDate",
      align: "left",
      search: false,
      sortable: false,
      overHidden: true,
      width: 100,
      span: 24,
    },
    {
      label: "状态",
      prop: "woTskStatusDesc",
      align: "left",
      search: false,
      sortable: false,
      overHidden: true,
      width: 100,
      span: 24,
    },
  ],
};
